### ISSUE TITLE
Give the option to output an aligned chart

### ISSUE THREAD

**Issue by RemySphere** [mkaz/termgraph#16]
It could be nice to have the option to format the output as left-aligned, based on labels length or given fixed width. It makes comparisons and overall output easier to read imo

Basic suggested impl:
```python
def horiontal_rows( labels, data, normal_dat, args, colors ):
    val_min = findMinMax( data, 'min' )
    
    # Find longest label for aligned output
    length_min = 0
    for i in range(len(labels)):
        if len(labels[i]) > length_min:
            length_min = len(labels[i])

    for i in range( len( labels ) ):
        if args['no_labels']:
            # Hide the labels.
            label = ''
        else:
            label = "{:<{x}}: ".format( labels[i], x = length_min )

...
```
Before:  
![image](https://user-images.githubusercontent.com/18334704/41718144-641edf00-755c-11e8-9622-5294f2fdd9f5.png)

After: 
![image](https://user-images.githubusercontent.com/18334704/41718155-70ce8494-755c-11e8-8adb-c9f9d1e3bcb9.png)

**Comment by mkaz** [comment]
Thanks for the suggestion, I've implemented this and updated!
