### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by MGF15** [mkaz/termgraph#19]
some error 
```
  File "termgraph.py", line 163
    sys.stdout.write( f'\033[{color}m' ) # Start to write colorized.
                                     ^
SyntaxError: invalid syntax

```

i fix it by remove all "f"

sys.stdout.write( '\033[{color}m' )

**Comment by diplozoon** [comment]
@MGF15 
What is the version of Python you are using?
"f-strings" are only supported Python 3.6 or newer.

If you are using 3.6 or newer, I want to reproduce this err.
So, please tell me the source code you ran.

**Comment by MGF15** [comment]
i'm on python 2.7.6 & python 3.4.3

**Comment by MGF15** [comment]
yes it's about "f-strings" .
thanks
