### ISSUE TITLE
in Window10 --color option does not accept any value

### ISSUE THREAD

**Issue by cpkio** [mkaz/termgraph#22]
I've tried the examples provided in a readme, but never got any result: the error is always `argument --color: invalid choice`.

Python is 3.6.5

**Comment by mkaz** [comment]
I do not have access to a Windows 10 machine, but a couple of searches found that if you add `%*` at the end it might work. So something like:

```
termgraph data/ex4.dat --color {blue,red} --no-title %*
```
I think you might also be able to wrap them in quotes somehow, my guess is that brackets {} are being evaluated by the Windows shell differently, my initial attempts aren't working on Linux, but it might behave differently.

See:
* https://stackoverflow.com/questions/36016562/execution-of-python-script-with-parameter-and-windows10-doesnt-work

* https://eli.thegreenplace.net/2010/12/14/problem-passing-arguments-to-python-scripts-on-windows

**Comment by diplozoon** [comment]
Hello.

I use usually Windows 10.
So, I tried `python termgraph/termgraph.py data/ex4.dat --color {blue,red} --no-title %*`.
It didn't work.
But I tried `python termgraph/termgraph.py data/ex4.dat --color blue red`, it's fine.
I think that on Windows 10, arguments {red, blue} are passed as one argument.

Although this may not be related to the subject, an error occurred when passing the argument `--no-title.`

**Comment by DmitriyK-CPKIO** [comment]
Thank you, the most obvious solution eluded my mind. The script should be altered a bit for portability, this issue including.  The other is `echo` command behaviour in Windows, which outputs to pipeline the last quote symbol `"`, thus breaking the `echo "Label,3,9,1" | termgraph --custom-tick "+" --no-title --no-label` command.

**Comment by mkaz** [comment]
Fixed in #42
