### ISSUE TITLE
Argument --no-title does not work

### ISSUE THREAD

**Issue by jserv** [mkaz/termgraph#25]
File `README.md` mentioned several examples, and the ones contains argument `--no-title` are not functioned as expected.
```
$ echo "Label,3,9,1" | termgraph --custom-tick "😀" --no-title --no-labels
termgraph: error: unrecognized arguments: --no-title
```

**Comment by diplozoon** [comment]
@jserv Hi, I was curious about the same things.
mkaz says the `--no-title` argument was old from when the title was shown by default, now there is no title by default.
The document has been updated.
Thanks.
