### ISSUE TITLE
Compatibility issues with Python versions <= 3.6

### ISSUE THREAD

**Issue by xrefor** [mkaz/termgraph#28]
I cant initialize the termgraph command. Neither for 2.7 or 3.5:

I installed via pip and pip3

python 2.7:
```
odit@atlas:pts/0->/home/odit (0) 
> termgraph
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/termgraph", line 7, in <module>
    from termgraph.termgraph import main
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.14_4/lib/python2.7/site-packages/termgraph/termgraph.py", line 172
    sys.stdout.write( f'\033[{color}m' ) # Start to write colorized.
                                     ^
SyntaxError: invalid syntax

```
Python3.5:
```
Traceback (most recent call last):
  File "/home/odit/.local/bin/termgraph", line 7, in <module>
    from termgraph.termgraph import main
  File "/home/odit/.local/lib/python3.5/site-packages/termgraph/termgraph.py", line 172
    sys.stdout.write( f'\033[{color}m' ) # Start to write colorized.
                                     ^
SyntaxError: invalid syntax
```

**Comment by sminez** [comment]
Termgraph is using f strings which are >=python 3.6. So either you need to replace all of the string formatting calls with version compatible syntax (format or %) or setup.py needs to restrict to being strictly 3.6 and above.

**Comment by BoltzmannBrain** [comment]
Running into this as well w/ Python 2.7. There's an f-string backport available: https://github.com/asottile/future-fstrings. Pip install that, and change the top of termgraph.py to:
```
#!/usr/bin/env python3
# -*- coding: future_fstrings -*-
# coding=utf-8
```

**Comment by mkaz** [comment]
@BoltzmannBrain fix will almost work for Python2. 

You will also need to change the following
```
from itertools import zip_longest as zip_longest
```
to
```
from itertools import zip_longest as izip_longest
```
which is possible to do via a conditional, but the future strings line fails on python3 which I'm not sure why.

With #38 and termgraph v0.2.0 we specified support only for 3.6 and up, which isn't really a solution if you can't upgrade or want to use on an older version.

**Comment by mkaz** [comment]
I merged the changes that removed f-strings which allows for python 3.5 compatibility.
There are no plans to make it compatible with python2.
