### ISSUE TITLE
PEP8 and other issues

### ISSUE THREAD

**Issue by nnist** [mkaz/termgraph#30]
The code currently does not follow [PEP8](https://www.python.org/dev/peps/pep-00080). By following the style guide, the code would be more readable, consistency would be better and it would be easier to maintain.

When I run `pylint` on `termgraph.py`, it outputs a large amount of warnings:
- Spaces before and after `()` and `[]`, i.e. `parser.add_argument( '--title', help='Title of graph' )` should be `parser.add_argument('--title', help='Title of graph')`
- Lines too long (should be 79 chars at maximum)
- Lots of unused imports from wildcard imports (wildcard imports should be avoided)
- Import order is wrong

It might also be better to use classes and a more object-oriented approach. This would make it more organized, easier to build upon and easier to re-use in other projects. Although this might better be filed as a new issue.

**Comment by mkaz** [comment]
Thanks @nnist for the nudge, I'll go through and lint the code.

My full-time job is working on WordPress, whose formatting style is lots of spaces, so when working on other projects, I tend to fallback to including extra spaces everywhere.
