### ISSUE TITLE
Bad display with --stacked

### ISSUE THREAD

**Issue by justUmen** [mkaz/termgraph#37]
The display in column doesn't work properly with the --stacked option.

```
Example1: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 22.00
Longertext example : ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 36.00
```

I have to use `column -t -s ':'` to clean it up.

**Comment by diplozoon** [comment]
Have you tried this?
 `termgraph data/ex7.dat --color {yellow,magenta} --stacked --title "Stacked Data"`

Also please tell me the situation in detail.

**Comment by justUmen** [comment]
Here are two full examples :

The good one without --stacked.

`echo -e "LOOOOOOOOOOOOOOOOOOOOOOOOONG LINE,10,20\nSHORT LINE,10,20"|termgraph --color {blue,red} --title BEAUTIFUL`

And the bad one with --stacked.
`echo -e "LOOOOOOOOOOOOOOOOOOOOOOOOONG LINE,10,20\nSHORT LINE,10,20"|termgraph --color {blue,red} --stacked --title UGLY`

**Comment by diplozoon** [comment]
To solve this problem, PR #40 was submitted by nnist.
Plz wait for mkaz to review it.
