### ISSUE TITLE
Use it as module

### ISSUE THREAD

**Issue by tbhaxor** [mkaz/termgraph#47]
Is this module available as a third-party module? If yes, how to integrate. If not, what are your plans?

**Comment by ckcollab** [comment]
I would like to it this directly from inside python as well! I'm not sure if there's a more documented way, but my plan now is to hit this function...

 https://github.com/mkaz/termgraph/blob/b10150d9d7c037ca9d11464d44316d12850a58c6/termgraph/termgraph.py#L352
