### ISSUE TITLE
Show int as int not float

### ISSUE THREAD

**Issue by kelvan** [mkaz/termgraph#5]
I'm using print_blocks in a script and only passing integers to it, but it always format it with decimal places.

**Comment by dufferzafar** [comment]
@kelvan The issue is [the format specifier](https://github.com/mkaz/termgraph/pull/6/files#diff-cf5d8e1fb71adc3d1d8e4c2d8e16d8a9L66)!

**Comment by mkaz** [comment]
@dufferzafar is correct, you can display the numbers any way you like using --format.
Here is an example which will remove the decimal and display as just integers.

```
> termgraph.py data/ex2.dat --format '{:.0f}'

label    : ▇▇ 2
longlabel: ▇▇▇ 3
foo      : ▇▇▇▇ 4
barrific : ▇▇▇▇▇ 5
wut      : ▇▇▇▇▇▇ 6

```
