### ISSUE TITLE
Last release is backwards incompatible

### ISSUE THREAD

**Issue by boxed** [mkaz/termgraph#57]
The last release crashes on my https://github.com/boxed/test-benchmarks project.

https://github.com/mkaz/termgraph/blob/master/termgraph/termgraph.py#L420
https://github.com/mkaz/termgraph/blob/master/termgraph/termgraph.py#L220

These lines should presumably do `args.get('label_before')`. 

If I change to doing `.get` everything works for me at least.

**Comment by mkaz** [comment]
Ok, I think it is because I didn't have a default value.
I've updated to with get and added a default. Thanks!
