### ISSUE TITLE
Question regarding the format specifier

### ISSUE THREAD

**Issue by moravveji** [mkaz/termgraph#59]
Hi.

I am trying to create some stacked bar graphs, using integer values. However, the default format is `5.2f` float. trying to override that with e.g. `3d` literally prints out the `3d` to the r.h.s of each bar. See the attached figure.

How can I show integral values on the graph?

Thanks
Ehsan
![image](https://user-images.githubusercontent.com/6280576/82459628-753fd900-9ab8-11ea-98c3-d84f6a69431c.png)

**Comment by mkaz** [comment]
@moravveji  You can use it like so: `termgraph --format '{:3.0f}'`

Also, the numbers are treated floats, so use `f` instead of `d`. 

See this String Format Cookbook for help with syntax if you need something additional:
https://mkaz.blog/code/python-string-format-cookbook/

**Comment by moravveji** [comment]
Thanks a lot for the tip.
