### ISSUE TITLE
Is it possible to pipe in the output of sort | uniq -c? 

### ISSUE THREAD

**Issue by vertesy** [mkaz/termgraph#7]
Hello!

Is it possible to pipe in the output of sort | uniq -c?  
This a basic bash one liner to get distributions.

#### Issues:

- reverse order of data an label; 
- space separation

#### Pseudo Code

`grep "^." MyFile.tsv | cut -f2 | sort | uniq -c | sort -nr` yields

```
25401 1
23593 7
21999 0
21760 3
20276 4
19462 10
19301 8
18835 5
18413 6
```

Where the first column are the values, labels are after the white space.

`grep "^." MyFile.tsv | cut -f2 | sort | uniq -c | sort -nr | termplot.py` plots the  labels (that happen to be numeric as well)

```
25401: ▇▇    1
23593: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇    7
21999: |    0
21760: ▇▇▇▇▇▇    3
20276: ▇▇▇▇▇▇▇▇    4
19462: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇   10
19301: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇    8
18835: ▇▇▇▇▇▇▇▇▇▇    5
18413: ▇▇▇▇▇▇▇▇▇▇▇▇    6
18406: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇    9
17906: ▇▇▇▇    2
17153: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇   14
16755: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇   13
14757: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇   12
14531: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇   11
```

Thank you!
Abel

**Comment by lebinh** [comment]
@vertesy it's probably easier to put in a `awk '{print $2,$1}'` into your pipe before termplot

**Comment by vertesy** [comment]
@lebinh Terrific, works, thank you!
