### ISSUE TITLE
💝 Thank you for your cool software 🎆 

### ISSUE THREAD

**Issue by adriens** [mkaz/termgraph#78]
# Context

Recently I wanted to make a data analysis chronicle, only with terminal based tools. Then I found `termgraph` <3

Finally I could implement my idea.... even better than expected, so I wanted to thank you for your great tool and show yo can could be achieved thanks to your software : 
 
- [Full Katacoda scenario](https://www.katacoda.com/glialabs/courses/postgresql/covid-psql)
- [Dedicated and compact DEV.to post](https://dev.to/adriens/draw-charts-from-terminal-with-psql-and-termgraph-50k6)
- [Youtube demo](https://youtu.be/kXwSfVa1yBA)

Hopefully you'll like it.

Kind Regards;
Adrien

**Comment by mkaz** [comment]
Thanks, glad you're finding a good use of it 👍
