### ISSUE TITLE
Annotations support only works in Python3.7+, not 3.5+ as specified in the docs

### ISSUE THREAD

**Issue by neil-greenwood** [mkaz/termgraph#84]
https://www.python.org/dev/peps/pep-0563/#enabling-the-future-behavior-in-python-3-7

README.md states that the minimum version is Python 3.5+, but that is incorrect.

**Comment by neil-greenwood** [comment]
❤️  Thanks for the speedy update!

**Comment by mkaz** [comment]
Thanks @neil-greenwood for the report 👍
